# Generated by Django 5.0 on 2023-12-06 21:57

import django.db.models.deletion
import product.validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("anatomi", "Anatomi"),
                            ("biokimya", "Biyokimya"),
                            ("farmakoloji", "Farmakoloji"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, default="3 Month", max_length=50, null=True
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="videos/", validators=[product.validator.file_size]
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["slug", "available"], name="product_vid_slug_7d729b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True, default="0", max_length=255, null=True
                    ),
                ),
                ("review", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.videomodel",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
