# Generated by Django 5.0 on 2023-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodel",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
