# Generated by Django 5.0 on 2023-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_videomodel_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodel",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
